[package]
name = "learning_docs"
version = "0.1.0"
authors = ["Oliver Wright <44814748+OWright3@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4.0"